feat: show covered video if heroVideo has data
mirror-media/mirror-media-nuxt pull request #283
Opened 2021-03-03 07:56 UTC by kjwen310

1. 在 premium 情況下(目前以style=wide表示)，story頁若存在影片( heroVideo )，則影片為滿版。
2. 影片寬高與形式已在 local 和 Tin 確認過，在行動裝置中會持續縮窄，在桌機中上下會被部分切除，文字維持壓在影片上。

2021-03-03 11:02 UTC, yeefun requested changes

2021-03-03 11:02 UTC, yeefun commented on components/culture-post/ContainerCulturePost.vue
> +    },
建議包成 heroVideo 物件，放在 post 裡頭，可以參考 post.coverPicture 是怎麼做的

2021-03-03 11:02 UTC, yeefun commented on components/culture-post/UiTheCover.vue
> +    />
有現成的 component 可以直接用：https://github.com/mirror-media/mirror-media-nuxt/blob/dev/components/UiStoryVideo.vue

2021-03-03 16:38 UTC, kjwen310 commented on components/culture-post/ContainerCulturePost.vue
> +    },
Resolved by [8b8003a](https://github.com/mirror-media/mirror-media-nuxt/pull/283/commits/8b8003a23ae07cbdca6d98d2ab1985f140de70c3)

為與 `post.coverPicture` 名稱一致，我將它命名為 `coverVideo`

2021-03-03 16:39 UTC, kjwen310 commented on components/culture-post/ContainerCulturePost.vue
> -
Resolved by [8b8003a](https://github.com/mirror-media/mirror-media-nuxt/pull/283/commits/8b8003a23ae07cbdca6d98d2ab1985f140de70c3)

2021-03-03 16:44 UTC, kjwen310 commented on components/culture-post/UiTheCover.vue
> +    />
謝謝，我有注意到這個元件，但因為css的部分不一致(UiStoryVideo內的`video {
  width: 100%;
  outline: none;
  object-fit: cover;
}`，需要增加`position: absolute;
  height: 100%;`才能符合需求)，是否仍要使用呢？

2021-03-04 03:13 UTC, yeefun commented on components/culture-post/UiTheCover.vue
> +    />
可以在組件外層新增 CSS

2021-03-04 03:17 UTC, yeefun requested changes

2021-03-04 03:17 UTC, yeefun commented on components/culture-post/ContainerCulturePost.vue
> +        },
既然都用 coverVideo 包起來了，就沒有必要在屬性取名上重複 video，可直接用 src、poster

2021-03-04 04:04 UTC, kjwen310 commented on components/culture-post/ContainerCulturePost.vue
> +        },
Resolved by [901982e](url)

2021-03-04 04:05 UTC, kjwen310 commented on components/culture-post/UiTheCover.vue
> +    />
Resolved by [24d425b](https://github.com/mirror-media/mirror-media-nuxt/pull/283/commits/24d425bc032146ccd4165d8d15cec35f654d6721)

2021-03-04 05:35 UTC, yeefun requested changes

2021-03-04 05:35 UTC, yeefun commented on components/culture-post/ContainerCulturePost.vue
> +        heroVideo.coverPhoto?.image?.resizedTargets?.mobile?.url || false
這邊這樣取名就不清楚了，建議跟這個 https://github.com/mirror-media/mirror-media-nuxt/pull/283/commits/8b8003a23ae07cbdca6d98d2ab1985f140de70c3 取同樣的名字，底下就寫：
```javascript
coverVideo: {
  src: heroVideoSrc,
  poster: heroVideoPoster,
},
```

2021-03-04 05:35 UTC, yeefun commented on components/culture-post/UiTheCover.vue
> +    },
這邊這樣取名就不清楚了，建議跟這個 https://github.com/mirror-media/mirror-media-nuxt/pull/283/commits/8b8003a23ae07cbdca6d98d2ab1985f140de70c3 取同樣的名字

2021-03-04 05:35 UTC, yeefun commented on components/culture-post/ContainerCulturePost.vue
> +      const src = heroVideo.video?.url || false
這裡 src 的預設值是 `false`，但 UiStoryVideo 組件的 src prop 並不支援這個 type，要嘛讓它的預設值是空字串，要嘛就不給預設值

2021-03-04 06:05 UTC, kjwen310 commented on components/culture-post/ContainerCulturePost.vue
> +      const src = heroVideo.video?.url || false
Resolved by [3dbe8d8](https://github.com/mirror-media/mirror-media-nuxt/pull/283/commits/3dbe8d8b2aa12ab40595cc99d13f1704be2597cb)

2021-03-04 06:05 UTC, kjwen310 commented on components/culture-post/UiTheCover.vue
> +    },
Resolved by [3dbe8d8](https://github.com/mirror-media/mirror-media-nuxt/pull/283/commits/3dbe8d8b2aa12ab40595cc99d13f1704be2597cb)

2021-03-04 06:05 UTC, kjwen310 commented on components/culture-post/ContainerCulturePost.vue
> +        heroVideo.coverPhoto?.image?.resizedTargets?.mobile?.url || false
Resolved by [3dbe8d8](https://github.com/mirror-media/mirror-media-nuxt/pull/283/commits/3dbe8d8b2aa12ab40595cc99d13f1704be2597cb)

2021-03-04 06:07 UTC, yeefun approved these changes

2021-03-04 06:08 UTC, yeefun approved these changes

2021-03-04 06:10 UTC, merged