fix: fix embedded code display problem
mirror-media/mirror-media-nuxt pull request #290
Opened 2021-03-15 11:13 UTC by kjwen310

修正 embedded code 的顯示問題

2021-03-16 03:51 UTC, yeefun requested changes
這個功能可以在別的地方共用（比如說會員文章），建議拆成組件。

2021-03-16 08:11 UTC, yeefun requested changes

2021-03-16 08:39 UTC, kjwen310 commented on components/UiStoryContentHandler.vue
> +                onLoad={() => renderScriptInbody(scripts)}
Resolved by [1c6451a](https://github.com/mirror-media/mirror-media-nuxt/pull/290/commits/1c6451a9f01408d4f600ba27bcb8cc3c671dbc38)

2021-03-16 08:40 UTC, kjwen310 commented
> 這個功能可以在別的地方共用（比如說會員文章），建議拆成組件。

Resolved by [1c6451a](https://github.com/mirror-media/mirror-media-nuxt/pull/290/commits/1c6451a9f01408d4f600ba27bcb8cc3c671dbc38)

2021-03-17 03:20 UTC, yeefun requested changes

2021-03-17 03:20 UTC, yeefun commented on components/UiEmbeddedCode.vue
> +export default {
這個專案的 component 都會給 name，這裡也給個 name 吧。

2021-03-17 03:20 UTC, yeefun commented on components/UiEmbeddedCode.vue
> +    <p v-if="caption" class="g-story-caption">{{ caption }}</p>
畢竟是組件了，圖說的樣式不應該依賴全局樣式？應該自己本身要有樣式，可以直接把 `g-story-caption` 的樣式內聯到組件裡頭。

2021-03-17 06:45 UTC, kjwen310 commented on components/UiEmbeddedCode.vue
> +    <p v-if="caption" class="g-story-caption">{{ caption }}</p>
Resolved by [6b670df](https://github.com/mirror-media/mirror-media-nuxt/pull/290/commits/6b670dfca1dbc7362f78cda3d5dc78d330a7d098)

2021-03-17 06:45 UTC, kjwen310 commented on components/UiEmbeddedCode.vue
> +export default {
Resolved by [6b670df](https://github.com/mirror-media/mirror-media-nuxt/pull/290/commits/6b670dfca1dbc7362f78cda3d5dc78d330a7d098)

2021-03-17 07:07 UTC, yeefun approved these changes

2021-03-17 07:07 UTC, merged