style: magazine-subscribe success UI adjust
mirror-media/mirror-media-nuxt pull request #339
Opened 2021-07-13 07:33 UTC by v61265

**說明**
- 紙本雜誌訂閱成功頁面 UI 微調

**參考資料**
- [Asana 卡片](https://app.asana.com/0/1200570778319695/1200582951827915)
- [文件](https://paper.dropbox.com/doc/jgnC27r3xclTCRRfCdqUi#:h2=UI-%E8%AA%BF%E6%95%B4)
- 路由：`/papermag/result` （須從 `/papermag` 進入）

2021-07-13 09:15 UTC, kwhsiung requested changes

2021-07-13 09:15 UTC, kwhsiung commented on components/SubscribeSuccessOrderInfo.vue
> +  font-size: 20px;
這部分看[設計稿](https://www.figma.com/file/qmocxMBHG6D7T2VPdydRWG/%E9%8F%A1%E9%80%B1%E5%88%8A-%E7%B6%B2%E7%AB%99?node-id=3202%3A10780)應該需要做 media query，手機版為 `18px`，並且無論哪個尺寸 `font-weight` 應該要設為 `500`

2021-07-13 09:15 UTC, kwhsiung commented on components/UiSubscribeInfo.vue
> +    font-size: 24px;
這部分也是，看[設計稿](https://www.figma.com/file/qmocxMBHG6D7T2VPdydRWG/%E9%8F%A1%E9%80%B1%E5%88%8A-%E7%B6%B2%E7%AB%99?node-id=3250%3A10950)應該需要做 media query，手機版為 `22px`。

2021-07-13 10:29 UTC, v61265 commented
不好意思剛剛沒看清楚，已經針對上面 review 調整了，再麻煩 @kwhsiung 看看，感謝～

2021-07-14 02:15 UTC, kwhsiung approved these changes
LGTM

2021-07-14 05:40 UTC, merged