feat: create survice-rule page and check if read before login
mirror-media/mirror-media-nuxt pull request #368
Opened 2021-08-03 03:53 UTC by v61265

描述：
- 新增「服務條款」頁面
- 若曾勾選過同意條款，則紀錄於 cookie 中
- 進入登入頁面時檢查是否有 cookie 紀錄，若沒有則進入服務條款頁面
- 勾選後會回到登入頁面，並照樣於登入後回到原本在閱讀的頁面

參考資料：
- [Asana 卡片](https://app.asana.com/0/1200640136089459/1200546112820288)
- [設計稿](https://www.figma.com/file/qmocxMBHG6D7T2VPdydRWG/%E9%8F%A1%E9%80%B1%E5%88%8A---%E7%B6%B2%E7%AB%99?node-id=3277%3A11196)

2021-08-03 06:43 UTC, kwhsiung commented
先就疑問回答
>1. /login 和 /loginNew 的差別？

`pages/login.vue` 屬 legacy code，是從前 [email link](https://firebase.google.com/docs/auth/web/email-link-auth) 登入方式使用的邏輯，目前因為改用 [email password](https://firebase.google.com/docs/auth/web/password-auth) 所以沒有再使用了，其實可以砍掉。
目前 `/login` 吃的是 `pages/loginNew.vue`，可見 [`nuxt.config.js`](https://github.com/mirror-media/mirror-media-nuxt/blob/dev/nuxt.config.js#L520-L529)。

>2. 目前只有 newLogin.vue 的檔案有檢查，看起來所有頁面都會經過 /login ，這樣還有其他 page 也需要檢查嗎？

不太清楚你的檢查室檢查什麼呢／

2021-08-03 10:36 UTC, kwhsiung requested changes

2021-08-03 10:36 UTC, kwhsiung commented on pages/service-rule.vue
> +        this.$store.dispatch('partners/fetchPartnersData'),
這個 fetch 可以先拿掉，確認是用不到的功能（以前 header 上的舊功能）

2021-08-03 10:36 UTC, kwhsiung commented on pages/service-rule.vue
> +      fetchPartnersAndTopicsData(),
這裡不應該從 membership gateway 拉文章資料，檢視一下拉回來的服務條款內容，你會發現被截斷了（三、會員責任及義務後的內容都不見了），這是 membership gateway 的功能之一，將會員專屬文章的內容以截斷呈現，鼓勵使用者登入會員後才能看到全文，而服務條款應完全不需要這種功能。

拉一般文章請改用 [fetchPosts](https://github.com/mirror-media/mirror-media-nuxt/blob/dev/plugins/requests/index.js#L220)：
```js
this.$fetchPosts(
  {
    slug: 'service-rule',
    isAudioSiteOnly: false,
    clean: 'content',
    related: 'article',
  }
)
```

2021-08-03 10:36 UTC, kwhsiung commented on pages/service-rule.vue
> +  },
由於拉文章由 `$fetchPostsFromMembershipGateway` 改成 `$fetchPosts`，跟會員狀態有關的邏輯應該可以拿掉了。

2021-08-03 10:39 UTC, kwhsiung requested changes

2021-08-03 10:39 UTC, kwhsiung commented on pages/service-rule.vue
> +      ),
這裡不應該從 membership gateway 拉文章資料，檢視一下拉回來的服務條款內容，你會發現被截斷了（三、會員責任及義務後的內容都不見了），這是 membership gateway 的功能之一，將會員專屬文章的內容以截斷呈現，鼓勵使用者登入會員後才能看到全文，而服務條款應完全不需要這種功能。

拉一般文章請改用 [fetchPosts](https://github.com/mirror-media/mirror-media-nuxt/blob/dev/plugins/requests/index.js#L220)：
```js
this.$fetchPosts(
  {
    slug: 'service-rule',
    isAudioSiteOnly: false,
    clean: 'content',
    related: 'article',
  }
)
```

2021-08-03 10:39 UTC, kwhsiung commented on pages/service-rule.vue
> +    }
由於拉文章由 `$fetchPostsFromMembershipGateway` 改成 `$fetchPosts`，跟會員狀態有關的邏輯應該可以拿掉了。

2021-08-03 10:46 UTC, kwhsiung commented on pages/service-rule.vue
> +      Cookie.set('read-service-rule', true, { expires: '30m' })
每過 30 分鐘會員就要重新同意一次會員條款？這樣有點怪

2021-08-04 07:01 UTC, v61265 commented
> 不太清楚你的檢查室檢查什麼呢？

原本預計是「沒有勾過服務條款，就無法登入」，所以希望能在所有可以登入的 page 都檢查是否有勾過服務條款。不過目前看來該方法會造成「同個瀏覽器登入不同帳號時，無法確保所有帳號都看過」，所以決定該 PR 先不包含流程控制。

### 更改描述
- 移除 `login` 頁面流程判斷。
- 更改和會員有關的 fetch ，改成拿取一般文章資料。
- 更改 cookie 的時間為十年。

2021-08-06 08:18 UTC, kwhsiung approved these changes
LGTM 🚀

2021-08-06 09:14 UTC, merged