feat: subscribe route and cancel page UI
mirror-media/mirror-media-nuxt pull request #370
Opened 2021-08-04 05:00 UTC by v61265

### 描述
- 新增會員訂閱頁面路由
- 新增取消訂閱頁（/subscribe/cancel-ask）
- 新增取消成功頁（subscribe/cancel-success）
- 新增取消失敗頁（subscribe/cancel-fail）
- 新增取消頁模擬小工具（是否用 App 付款 / 取消成功與否）

### Question
- 取消訂閱頁的 checkbox 目前直接被包在 `SubscribeCancel.vue` ，不過和其他三個有點不一致，是否需要再切一個 component（不過重複使用機率也不高）或用 slot 直接寫在 page 中？
- 模擬工具（SubscribeCancelSimForm）改變 `cancelStatus` 時跳出警告，說不要直接改變 props ，不過作法類似的 `clickHandler` 就沒有類似問題，想請教我是否漏掉什麼。

### 參考資料
- [Asana 卡片 - 取消訂閱頁](https://app.asana.com/0/1200640136089459/1200581396911925)、[Asana 卡片 - 取消結果頁](https://app.asana.com/0/1200640136089459/1200646414580217)
- [會員訂閱頁面 PRD](https://paper.dropbox.com/doc/PRD--BPzlvJ_sLZ33TAcqn4wia7_TAg-r3yPzn9K2wU5fUI5cy37F)
- [設計稿](https://www.figma.com/file/qmocxMBHG6D7T2VPdydRWG/%E9%8F%A1%E9%80%B1%E5%88%8A---%E7%B6%B2%E7%AB%99?node-id=2822%3A6801)

2021-08-05 15:44 UTC, liyibass commented on components/SubscribeCancel.vue
> +      <label for="content">
回應Question 1:
若是我的話，我會把checkbox們切出來當個單一的component
因為我會比較傾向每個vue檔案包含的程式碼||邏輯越少越單純越好


### PS.以下是參考 並不一定要修改，可以看看就好！
另外
這個SubscribeCancel其實在四個區塊有被用到：
- isPayByApp的提示 （cancel-ask）
- 充滿了checkbox的畫面（cancel-ask）
- 成功取消訂閱（cancel-success）
- 取消訂閱失敗（cancel-fail）

目前都是在不同頁面將不同的props傳入SubscribeCancel中
並在SubscribeCancel裡頭邏輯判斷要顯示出四個中的那一個內容
頁面（工作邏輯輕鬆）
SubscribeCancel（工作邏輯繁重）

若是我的話，或許會選擇讓SubscribeCancel單純地當一個wrapper就好
在其中一個頁面就可以像下面這樣：
```
    <SubscribeCancel v-if="isPayByApp">
      <h6>取消訂閱提示</h6>
      <p>
        由於您先前於 APP 購買，如要取消訂閱，請至 App Store (iOS 系統) 或 Google
        Play (Android 系統) 操作
      </p>

      <UiMembershipButtonPrimary
        class="subscribe-cancel__back"
        @click.native="() => $emit('back')"
        >回訂閱紀錄</UiMembershipButtonPrimary
      >
    </SubscribeCancel>
```
讓各自頁面自己決定內容顯示什麼，而SubscribeCancel就負責裡面style的樣式

2021-08-06 09:24 UTC, kwhsiung requested changes

2021-08-06 09:24 UTC, kwhsiung commented on pages/subscribe/cancel-ask.vue
> +      return process.env.NODE_ENV !== ('production' || 'staging')
1. 這裡應該要用 config 中的 `ENV`，而不是 `NODE_ENV`，可能是遺漏了。
2. 另外這裡的邏輯判斷可能不會是你預期的結果，舉例來說：
```
'staging' !== ('production' || 'staging') // return true, but we want false
```

2021-08-09 06:51 UTC, v61265 commented
## commits 修改說明
- 將 SubscribeCancel 改成 SubscribeWrapper，並只包含 wrapper 功能，邏輯和內容分散於個頁中。 [參考 review](https://github.com/mirror-media/mirror-media-nuxt/pull/370#discussion_r683574358)
- 將一組 checkout 和 label 抽出成 component。
- 修改 shouldShowSim 條件判斷。 [參考 review](https://github.com/mirror-media/mirror-media-nuxt/pull/370#discussion_r684087002)
- 新增 innerCancelStatus ，將資料改成單向綁定。[參考 review](https://github.com/mirror-media/mirror-media-nuxt/pull/370#discussion_r683528622)

2021-08-09 07:56 UTC, kwhsiung requested changes

2021-08-09 07:56 UTC, kwhsiung commented on pages/subscribe/cancel-ask.vue
> +      return process.env.ENV !== 'production' && process.env.ENV !== 'staging'
process.env.* 通常可以透過觀察 package.json 中 scripts 的 cross-env 設定來知道有什麼環境變數可用，譬如 [dev](https://github.com/mirror-media/mirror-media-nuxt/blob/dev/package.json#L8) 與 [start](https://github.com/mirror-media/mirror-media-nuxt/blob/dev/package.json#L10)，你可以發現到其實沒有設定 `ENV`，所以 `process.env.ENV` 應該為 falsy 才是。

`ENV` 我們是定義在 config 中，譬如說[以 prod 為例子](https://source.cloud.google.com/mirrormedia-1470651750304/configs/+/master:mirror-media/mirror-media-nuxt/prod/config.js;l=11?authuser=2&hl=zh-TW)，所以應該是這樣拿才對
```js
import { ENV } from '~/configs/config`

ENV !== 'production' && ENV !== 'staging'
```

2021-08-09 07:57 UTC, kwhsiung commented
這個 commit 打錯字了：https://github.com/mirror-media/mirror-media-nuxt/pull/370/commits/c46fee4941c3c5542f81d83ab38b54555a9bf4d3
所以造成 Semantic Pull Request 沒過，可能要修改一下。

2021-08-10 02:41 UTC, v61265 commented
### commit 說明
- 修改 ENV 變數來源
- 修改 `[99f61b4](https://github.com/mirror-media/mirror-media-nuxt/pull/370/commits/99f61b46eccc4392800999d863cd36e05b838c3a)` 命名

2021-08-10 05:34 UTC, kwhsiung requested changes

2021-08-10 05:34 UTC, kwhsiung commented on pages/subscribe/cancel-ask.vue
> +      return ENV !== 'production' && ENV !== 'staging'
正式機的 ENV 應該是 'prod' 而不是 'production'，所以預期到時候上到正式機小工具應該會顯示出來。
參考：
  https://github.com/mirror-media/mirror-media-nuxt/pull/372/files#diff-54d805d8796b04a32801d2e40598152c81e47a23c611ac58b3db0fc509f876d8R205
  https://source.cloud.google.com/mirrormedia-1470651750304/configs/+/master:mirror-media/mirror-media-nuxt/prod/config.js;l=11?q=mirror-media&authuser=2&hl=zh-TW

2021-08-10 06:38 UTC, kwhsiung approved these changes

2021-08-10 06:53 UTC, merged