feat: subscribe-choose-plan page
mirror-media/mirror-media-nuxt pull request #372
Opened 2021-08-05 06:19 UTC by v61265

### 描述
- 新增方案選擇頁 & 方案升級頁 `/subscribe`
- 新增 debug 小工具，調控會員狀態（非會員 / 普通會員 / 月訂閱會員 / 年訂閱會員）
- 修改 component `UiSubscribeButton` 顏色改為 origin / grey /light。
- 修改 component `UiSubscribeInfo` 和紙本雜誌訂閱共用「注意事項」區塊。

### TODO
- 年訂閱會員頁面 >> 可直接使用[取消訂閱 component](https://github.com/mirror-media/mirror-media-nuxt/pull/370) ，待都 merge 後另發 PR 處理。
- 進入方案選擇頁和成為會員的按鈕連結。

### 參考資料
- [Asana 卡片](https://app.asana.com/0/1200640136089459/1200581396911923)
- [會員訂閱頁面 PRD](https://paper.dropbox.com/doc/PRD--BPzlvJ_sLZ33TAcqn4wia7_TAg-r3yPzn9K2wU5fUI5cy37F)
- [設計稿](https://www.figma.com/file/qmocxMBHG6D7T2VPdydRWG/%E9%8F%A1%E9%80%B1%E5%88%8A---%E7%B6%B2%E7%AB%99?node-id=2822%3A6801)

2021-08-05 14:04 UTC, liyibass commented on components/SubscribeMembershipChoosePlanCard.vue
> +        <div v-if="ps !== ''" class="plan-card__button_group_ps">{{ ps }}</div>
這裡的v-if可以再寫的更簡潔一些
詳情我下方會說～

2021-08-06 01:59 UTC, v61265 commented
### commit 修改
- 修改 `ps` 變成 `hintUnderButton`（因為按鈕中有個 props 就叫 `hint` ，怕混淆所以區分開來）
- 修改 titile 標籤為 `h2`
- 修改按鈕連結為 `subscribe/info`

2021-08-06 08:50 UTC, kwhsiung requested changes

2021-08-06 08:50 UTC, kwhsiung commented on pages/subscribe/index.vue
> +const { ENV } = require('../../configs/config')
在 client side 請使用 ES6 import: `import { ENV } from '~/configs/config'`

2021-08-06 08:50 UTC, kwhsiung commented on pages/subscribe/index.vue
> +    },
nit(not critical): 雖然可以正常運作，但對單一個資料結構依條件做一系列 mutations 後回傳可能會較難理解以及重構 ，其實不如直接為 `month`, `basic`, `default` 三種狀態直接生出三個獨立的資料結構，再依條件直接回傳，換句話說 switch case 沒有問題，但目前的 case 內的 logics 可能可以更好。

2021-08-09 07:06 UTC, v61265 commented
## commit 修改
- env import 方式。[參考 review](https://github.com/mirror-media/mirror-media-nuxt/pull/372#discussion_r684061241)
- 修改 `planShowed` 內的邏輯。[參考 review](https://github.com/mirror-media/mirror-media-nuxt/pull/372#discussion_r684067013)

2021-08-09 08:01 UTC, kwhsiung requested changes

2021-08-09 08:01 UTC, kwhsiung commented on pages/subscribe/index.vue
> +const { ENV } = require('~/configs/config')
這裡還是需要更改一下引入方式喔，目前還是使用 require 的 CommonJS 形式。
參考 https://github.com/mirror-media/mirror-media-nuxt/pull/372#discussion_r684061241

2021-08-10 05:30 UTC, kwhsiung approved these changes

2021-08-10 05:59 UTC, merged