feat: papermag add israfel and redirect to newebpay
mirror-media/mirror-media-nuxt pull request #489
Opened 2022-01-14 03:01 UTC by v61265

### 描述
- 紙本雜誌訂閱
- [encrypt draft order and redirect to NewebPay MPG web page](https://app.asana.com/0/1201617285674159/1201496734039775)
- [request Backend API Server to get a draft order](https://app.asana.com/0/1201617285674159/1201496734039774)

2022-01-14 03:21 UTC, nickhsine commented on utils/papermagSubscribe.js
> +    'http://localhost:3000/papermag/return'
`ReturnURL` 之後會改成從環境變數裡拿嗎？

2022-01-14 03:21 UTC, nickhsine commented on utils/papermagSubscribe.js
> +      ReturnURL
就目前的設計，`ReturnURL` 在前端決定，所以可以刪除 `ReturnURL`。

2022-01-14 03:21 UTC, nickhsine commented on utils/papermagSubscribe.js
> +      url: 'https://dev-israfel-gql.mirrormedia.mg/api/graphql',
israfel endpoint 是否從環境變數中讀取？

2022-01-14 03:21 UTC, nickhsine commented on utils/papermagSubscribe.js
> +        'Cache-Control': 'no-store',
想請問這裡加上 `Cache-Control: no-store` 的用意是？

2022-01-14 03:21 UTC, nickhsine commented on pages/papermag/redirect/index.vue
> +        Version: parseFloat(queryString.Version),
`Version` 的 type 應該是 `string`？

2022-01-14 03:21 UTC, nickhsine commented on pages/papermag/_plan/index.vue
> +        tradeInfo.MerchantID = tradeInfo.merchantId
想請問為何前端會有 `merchantId`？

2022-01-14 03:39 UTC, v61265 commented on utils/papermagSubscribe.js
> +      ReturnURL
好的！另外目前還沒有 `NotifyURL` ，要麻煩後端寫一下，感謝～

2022-01-14 03:54 UTC, nickhsine commented on utils/papermagSubscribe.js
> +      ReturnURL
收到，補上再和你說。

2022-01-14 04:30 UTC, v61265 commented on utils/papermagSubscribe.js
> +    'http://localhost:3000/papermag/return'
對齁忘記改！

2022-01-14 04:34 UTC, liyibass commented on components/SubscribeForm.vue
> +      // }
這些沒有用的應該都可以拿掉了

2022-01-14 04:34 UTC, liyibass commented on components/SubscribeForm.vue
> +        // console.log(str)
同上 可以拿掉沒有用的舊code

2022-01-14 04:34 UTC, liyibass commented on pages/papermag/_plan/index.vue
> +        tradeInfo.MerchantID = tradeInfo.merchantId
這個是之前在測試paymentPayload時遺留的code
@v61265 記得把它拿掉唷！

2022-01-14 04:34 UTC, liyibass commented on pages/papermag/_plan/index.vue
> -        const paymentPayload = await this.$axios.$post(
這個區塊的comment eslint都有報warning
可以修正一下下！
（記得在comment上方空格）

2022-01-14 04:34 UTC, liyibass commented on pages/papermag/redirect/index.vue
> +        Version: parseFloat(queryString.Version),
@v61265 需要你修正一個東西
NewebpayForm.vue這個component
裡頭的prop需要更改version的type：
```
  props: {
    merchantId: {
      type: String,
      isRequired: true,
      default: '',
    },
    tradeInfo: {
      type: String,
      isRequired: true,
      default: '',
    },
    tradeSha: {
      type: String,
      isRequired: true,
      default: '',
    },
    version: {
      type: String,
      isRequired: true,
      default: '1.6',
    },
  },
  ```
  
  如此一來 這一邊的Version就可以直接querystring.Version傳入耳不用parseFloat了

2022-01-14 04:34 UTC, liyibass commented on pages/papermag/return/index.vue
> +      console.log({ payload, body })
console.log可以拿掉（包含整個papermag測試用的console.log都可以拿掉了）
（或是設定ENV=“prod”的時候要隱藏）

2022-01-14 04:34 UTC, liyibass commented on pages/papermag/return/index.vue
> +  },
這個可以直接拿掉

2022-01-14 04:34 UTC, liyibass commented on pages/papermag/return/index.vue
> +  // },
若是都沒有用到 就大膽地直接刪掉吧！

2022-01-14 04:34 UTC, liyibass commented on utils/papermagSubscribe.js
> +      url: 'https://dev-israfel-gql.mirrormedia.mg/api/graphql',
+1

2022-01-14 05:35 UTC, v61265 commented on utils/papermagSubscribe.js
> +        'Cache-Control': 'no-store',
這是參考之前會員訂閱打 post 的寫法，沒有 cache 感覺比較安全？

2022-01-14 05:47 UTC, nickhsine commented on utils/papermagSubscribe.js
> +        'Cache-Control': 'no-store',
如果是 request 要求 origin server 不要回傳 cached object 的話，
這邊應該是要帶 `Cache-Control: no-cache`。

2022-01-14 07:30 UTC, v61265 commented on pages/papermag/return/index.vue
> +      console.log({ payload, body })
這整塊其實還在施工，不過確實把功能分開一點比較好，先刪掉～

2022-01-14 07:33 UTC, v61265 commented
### commit 842da70
- 將 url 調整成隨 config 變化
- 調整 payload 格式
- 將多餘註解刪除

2022-01-14 07:49 UTC, nickhsine requested changes

2022-01-14 07:49 UTC, nickhsine commented on utils/papermagSubscribe.js
> +export { getPaymentDataOfPapermagSubscription, fireGqlRequest }
建議把此檔案的 `getPaymentDataOfPapermagSubscription`, `fireGqlRequest` 移到 `api/newebpay-papermag.js` 裡。

`ReturnURL` 不會出現 `http://localhost:3000` 等字眼，因為藍新會不知道回到哪個頁面去。

2022-01-14 08:02 UTC, nickhsine commented on pages/papermag/_plan/index.vue
> +        tradeInfo = qs.parse(tradeInfo)
想請問這邊為何要 `qs.parse(tradeInfo)`？
`tradeInfo` 不是一個 object  ？

2022-01-14 08:02 UTC, nickhsine commented on pages/papermag/_plan/index.vue
> +        this.$router.push(`/papermag/redirect?${queryString}`)
有兩個問題想問 🙋 
1. 為何要多一個 redirect（目前是 papermag/plan -> papermag/redirect -> newebpay page) ？
2. 用 query 的方式傳，會有 URL 長度限制，我們如何確保 encrpyt 字串不會長過 URL 限制？

2022-01-14 08:21 UTC, v61265 commented on pages/papermag/_plan/index.vue
> +        this.$router.push(`/papermag/redirect?${queryString}`)
1. 我來試試看！
2. 糟糕我沒想過這個問題......如果可以做到上一點省略 redirect 的話就可以避開了，不過如果還是要進入 redirect 是不是就要考慮其他方式了呢？

也想順便問 nick 之後會遇到的另一個情況：
目前設計是從藍新會來的資料會進入 `/return` 頁面解析 `req.body` 的資料，如果成功會導入 `/success` ，但此時還是需要從藍新回傳的資料，此時要怎麼將資料傳給  `/success`  頁面會比較好呢？

2022-01-14 08:23 UTC, nickhsine commented on pages/papermag/_plan/index.vue
> +        this.$router.push(`/papermag/redirect?${queryString}`)
> 目前設計是從藍新會來的資料會進入 /return 頁面解析 req.body 的資料，如果成功會導入 /success ，但此時還是需要從藍新回傳的資料，此時要怎麼將資料傳給 /success 頁面會比較好呢？

2022-01-14 08:27 UTC, nickhsine commented on pages/papermag/_plan/index.vue
> +        this.$router.push(`/papermag/redirect?${queryString}`)
> 糟糕我沒想過這個問題......如果可以做到上一點省略 redirect 的話就可以避開了，不過如果還是要進入 redirect 是不是就要考慮其他方式了呢？

就目前的寫法只要把 newebpay form component render 在 papermag/plan 頁面，是不是就可以省略一次跳轉？

2022-01-14 08:30 UTC, v61265 commented on pages/papermag/_plan/index.vue
> +        this.$router.push(`/papermag/redirect?${queryString}`)
了解！
對，目前的需求是導到 `/success` 和 `/fail` ，感覺確實都在 `/return` 頁完成比較單純，我來問問 PM～

2022-01-14 08:31 UTC, nickhsine commented on pages/papermag/_plan/index.vue
> +        this.$router.push(`/papermag/redirect?${queryString}`)
> > 目前設計是從藍新會來的資料會進入 /return 頁面解析 req.body 的資料，如果成功會導入 /success ，但此時還是需要從藍新回傳的資料，此時要怎麼將資料傳給 /success 頁面會比較好呢？
> 
> 目前的做法是用 redirect 的方式導去 `/success` 頁面嗎？ 如果是在 `/return` 頁面，用 components 的方式把 success component render 出來呢？

另外一個做法是 `/success` 頁面吃 `orderNumber` 的 query param，`/success` 頁面拿到 orderNumber 後，像 israfel 把其他資料要齊。

2022-01-14 15:48 UTC, v61265 commented
### 更動
1.  將 `getPaymentDataOfPapermagSubscription`, `fireGqlRequest` 移到 `api/newebpay-papermag.js`。
2. 移除 `redirect` 頁面，送出後直接轉跳藍新。

2022-01-14 15:51 UTC, v61265 commented on utils/papermagSubscribe.js
> +export { getPaymentDataOfPapermagSubscription, fireGqlRequest }
`ReturnURL` 的寫法是為了防止在 localhost 找不到 `location.origin`，到機器上都會有相對應網址。

2022-01-17 03:01 UTC, nickhsine commented on api/newebpay-papermag.js
> +const baseUrl = location.origin
`api/newebpay-papermag.js`  是不是在 server 端執行的程式碼？
想問我們有辦法拿到 `location.origin` 嗎？

2022-01-18 09:40 UTC, v61265 commented
## commit #2933ad6
- 在 `/papermag/return` 頁面解析藍新回傳資料，得到交易狀態和交易 id
- 用交易 id 進入 israfel 得到詳細資料
- 將資料顯示在頁面上（以上都在 `/papermag/return` 中）

## todo
- [x] 測試 fail 狀態
- [x] 將折扣碼顯示於頁面上
- [x] 若勾選「限時掛號」，則更改品項名稱
- [x] 將運費顯示於結果頁上
- [x] 在 gcp 上更新 config 檔案

2022-01-18 10:18 UTC, nickhsine commented on pages/papermag/return/index.vue
> +      )
想請問為何要發 request 回 server 去 decrypt？
在 `asyncData` 的 function 中（此 function 我預期會在 server 端執行），就可以拿到 req.body ，並將藍新回傳的 tradeInfo 解密，再根據解密後的節果，選擇要 render success compoent 或是 fail component。

2022-01-18 10:29 UTC, nickhsine commented on pages/papermag/_plan/index.vue
> +          `${window.location.origin}/api/v2/papermag/encrypt/v1`,
想請問 🙋 
encrypt 的部分為何也要從打 API？

2022-01-18 10:48 UTC, v61265 commented on pages/papermag/_plan/index.vue
> +          `${window.location.origin}/api/v2/papermag/encrypt/v1`,
這裡面包含兩個部分：
1. 打 israfle 新增資料 >> 如果不從前端 server 打會遇到 CORS
2. 從 israfel 拿回的資料加密 >> 這部分參考會員訂閱也是放在前端 server 裡面

2022-01-18 11:56 UTC, nickhsine commented on api/papermag/decrypt.js
> +const apiUrl = `${baseUrl}${API_PATH_FRONTEND}`
想請問 🙋 
`api/papermag/decrypt.js` 會在 client side 跑嗎？
我以為只會在 server side 跑。

2022-01-18 11:56 UTC, nickhsine commented on api/papermag/encrypt.js
> +const apiUrl = `${baseUrl}${API_PATH_FRONTEND}`
想請問 🙋
`api/papermag/encrypt.js` 會在 client side 跑嗎？
我以為只會在 server side 跑。

2022-01-18 11:56 UTC, nickhsine commented on pages/papermag/_plan/index.vue
> +          `${window.location.origin}/api/v2/papermag/encrypt/v1`,
謝謝說明，
因為取名的關係，我以為是只有做第二點（加密的部分）。
endpoint path 是否改一下會比較容易懂？

2022-01-18 12:09 UTC, nickhsine commented on pages/papermag/return/index.vue
> +      const infoData = qs.parse(body)
處理 req body 有官方 express built-in 套件可以用(https://expressjs.com/zh-tw/api.html#express.urlencoded)，
可以把套件放在 express middleware 中處理 req body。

2022-01-19 04:06 UTC, v61265 commented on pages/papermag/_plan/index.vue
> +          `${window.location.origin}/api/v2/papermag/encrypt/v1`,
那 path 如下：
`/encrypt.js` 改為 `/create-magazine-order-and-encrypt.js`
`/decrypt.js` 改為 `/decrypt-and-get-magazine-order.js`

> `${window.location.origin}/api/v2/papermag` 呢？
是指這部分的命名也不直觀嗎？

2022-01-19 06:23 UTC, v61265 commented
### 更新
- 將 `/api/papermag/decrypt.js` 放到 `/pages/papermag/return/index.vue` 的 `asyncData` 中處理。 
- apiUrl 改從環境變數拿
-  將 `/api/papermag/encrypt.js` 移到 `/api/papermag.js` 中。

2022-01-19 06:46 UTC, v61265 commented on pages/papermag/return/index.vue
> +      const infoData = qs.parse(body)
喔喔喔喔好酷，不過目前已經把這部分移至 nuxt 中了，雖然也可以再加 middleware 但麻煩程度好像差不多，這次就先不改了～

2022-01-19 07:15 UTC, v61265 commented
# commit 2523b8d
選擇「限時掛號」的話，在 merchandice 上視為選擇另一個商品，在藍新也可看到「加掛號運費」，另於付款成功頁可看到運費分開顯示。

2022-01-19 07:33 UTC, nickhsine commented on pages/papermag/return/index.vue
> +      const infoData = qs.parse(body)
建議使用官方的套件而不是自己刻 req body 的處理

2022-01-19 07:38 UTC, nickhsine commented on pages/papermag/return/index.vue
> +      const infoData = qs.parse(body)
https://github.com/expressjs/body-parser/blob/master/lib/types/urlencoded.js 
這是官方的 body parser 的程式碼，它有做了很多處理，
如果我們要自己刻，那些處理我們也得加上才行。
所以麻煩程度應該是自己刻難上許多... 😓

2022-01-19 07:54 UTC, nickhsine commented on api/papermag.js
> +  console.log('enter server')
log 記得拿掉。

2022-01-19 07:54 UTC, nickhsine commented on api/papermag.js
> +  ISRAFEL_PATH,
`PATH` 在 URL 裡的定義是網址後面的值，例如 `/api/graphql`。

因此建議改成 `ISRAFEL_URL`，其值是（舉例測試環境為例） `https"//dev-israfel-gql.mirrormedia.mg/api/graphql`。
或是改成 `ISRAFEL_ORIGIN`，其值是（舉例測試環境為例）`https://dev-israfel-gql.mirrormedia.mg`。

2022-01-19 07:54 UTC, nickhsine commented on api/papermag.js
> +    throw new Error(error.message)
好奇想知道為何要再 `new Error`？

2022-01-19 07:54 UTC, nickhsine commented on api/papermag.js
> +    res.send(e)
是否要回傳修飾過後的 error 給 client？
而非回傳 error object ？
關於 api 回傳的 format 可以參考 JSend （https://github.com/omniti-labs/jsend）。

2022-01-19 07:59 UTC, v61265 commented on api/papermag.js
> +    res.send(e)
這個和 `new Error` 都是搬運過程沒清乾淨的，我來清一下，感謝提醒！

2022-01-19 08:01 UTC, v61265 commented on api/papermag.js
> +    throw new Error(error.message)
對欸，我來改一下！

2022-01-19 08:06 UTC, v61265 commented on api/papermag.js
> +    throw new Error(error.message)
如果在該 function 內發生錯誤，應該會直接傳給觸發他的環境，是否表示這邊不用再 try catch 呢？

2022-01-19 08:12 UTC, nickhsine commented on api/papermag.js
> +    throw new Error(error.message)
我覺得可以省掉這個 try catch。

2022-01-19 09:14 UTC, v61265 commented on pages/papermag/return/index.vue
> +      const infoData = qs.parse(body)
目前解析資料的方法有幾種：
1. 想辦法直接用 `req.body` 拿到 >> 因為是資料格式是 form data，所以資料不在 `req.body` 中 QQ
2. 目前這個方法。
3. 在 nuxt 中直接使用官方套件 >> nuxt 中無法直接使用 express 套件。
4. 另外開一個 `serverMiddleware` >> 雖然可行，但會多耗資源又降低可讀性。

2022-01-19 10:08 UTC, v61265 commented
### 更新
- 根據上面 nick code review 調整。
- 新增 middleware 讓 `/papermag/return` 可以直接拿取 `req.body`。

2022-01-19 10:21 UTC, nickhsine commented on api/papermag.js
> +    })
根據 JSend 的設計，
400 是 client error，所以 response body 會是
```
{
  status: 'fail',
  data: 'THE FAIL REASON',
}
```

好奇我們這邊的錯誤會是 client error 還是 server error ？

2022-01-19 10:22 UTC, nickhsine commented on api/papermag.js
> +    res.send(encryptPostData)
另外，這邊也可以 follow JSend 的回傳格式喔。

2022-01-19 10:29 UTC, v61265 commented on api/papermag.js
> +    })
會在 server 端顯示

2022-01-19 14:54 UTC, v61265 commented on api/papermag.js
> +    })
記錄一下討論結果：此處先使用 server error 的方式，並發送 500。
```
{
      status: 'error',
      message: e.message,
}
```

2022-01-19 15:50 UTC, v61265 commented
## 更動
- 輸入優惠代碼時，一份少 80 元，並會顯示在結果頁上。
- 若還沒進入藍新就出錯，則進入 `/papermag/return?order-fail` 頁面，顯示 order-fail 結果。
- 若單純進入 `/papermag/return` 而沒帶藍新資料，則回到 `/papermag` 頁。
- 若藍新回傳錯誤訊息，則顯示於結果頁上。
- 更改 `~/api/papermag.js` 的回傳格式，以符合 JSend。

2022-01-20 02:40 UTC, nickhsine commented on pages/papermag/_plan/index.vue
> +        this.$router.push(`/papermag/return?order-fail=true`)
如果這邊是導到錯誤頁（`?order-fail=true`）的話，
那 Ln. 76 行是不是也要導到錯誤頁面？

2022-01-20 02:40 UTC, nickhsine commented on pages/papermag/return/index.vue
> +      status: false,
為何是 boolean ？

2022-01-20 02:56 UTC, v61265 commented
## 更新
- 修正小 bug（導到錯誤頁面時加上 query、`status` 預設值改成 'order-fail`）

2022-01-20 03:53 UTC, nickhsine commented on apollo/queries/papermagQuery.gql
> +  magazineOrder(where: { orderNumber: $orderNumber }) {
建議這邊用 `allMagazineOrders`，
範例：

```
query {
  magazineOrders: allMagazineOrders(where: {orderNumber: "${orderNumber}"}) {
    id
    orderNumber
    paymentStatus
  }
}
```

如果我們用 `magazineOrder` ，但是帶了一個不存在的 `orderNumber` 的話，
israfel 會回錯誤，
錯誤內容為 
```
{
  "errors": [
    {
      "message": "You do not have access to this resource",
      "name": "AccessDeniedError",
      "time_thrown": "2022-01-20T03:52:03.014Z",
      "data": {
        "type": "query"
      },
      "path": [
        "magazineOrder"
      ],
      "uid": "ckymfttqi000075s60a4x6oxb"
    }
  ],
  "data": {
    "magazineOrder": null
  }
}
```

改用 `allMagazineOrders` 的話，
israfel 只會回傳空陣列，而非錯誤。

2022-01-20 04:21 UTC, v61265 commented
## commit 6f87462
- 改用 `allMagazineOrders` 打資料，並新增找不到資料的錯誤處理。

2022-01-20 04:31 UTC, nickhsine commented on pages/papermag/return/index.vue
> +      const decryptInfoData = result.data.allMagazineOrders[0]
如果 `result.errors` 存在，`result.data` 可能會不存在，
所以 `result?.data?.allMagazineOreders[0]`  會比較安全。

2022-01-20 04:33 UTC, nickhsine commented on pages/papermag/return/index.vue
> +          },
小提醒，
這邊回傳的 object 看起來很多重複之處。
盡量減少重複的資訊會讓程式碼簡潔許多。

2022-01-20 04:42 UTC, v61265 commented
## 更新
- 用三元運算子讓 `decryptData` 避免錯誤
- 清理 data 中重複的 orderId ，讓程式碼更簡潔

2022-01-20 04:43 UTC, nickhsine commented
LGTM 👍 🥇

2022-01-20 04:44 UTC, nickhsine approved these changes

2022-01-20 08:59 UTC, merged