refactor: subscribe membership return process
mirror-media/mirror-media-nuxt pull request #571
Opened 2022-03-30 05:51 UTC by v61265

### 描述
- 會員訂閱付款結果重構

### TODO
- [ ] 新增 error log（另發 PR）

2022-04-12 04:25 UTC, nickhsine requested changes

2022-04-12 04:25 UTC, nickhsine commented on pages/subscribe/info.vue
> +        delete tradeInfo.ClientBackURL
想請問，我們為何要把 `ClientBackURL` 刪掉？

2022-04-12 04:25 UTC, nickhsine commented on pages/subscribe/return.vue
> +    if (req.method !== 'POST') redirect('/papermag')
兩點建議：
1. `redirect('/subscribe')`
2. 要記得加上 `return`，確保接下來的程式不會被執行。

2022-04-12 04:25 UTC, nickhsine commented on apollo/queries/memberSubscriptionQuery.gql
> +}
好奇問問，
為何我們會想將此 query 放在 apollo 裡面？

2022-04-12 04:25 UTC, nickhsine commented on pages/subscribe/return.vue
> +      if (result.errors) throw new Error(result.errors[0].message)
我們只處理第一個 error 的訊息嗎？
其他的 errors 的訊息呢？

2022-04-12 04:25 UTC, nickhsine commented on pages/subscribe/return.vue
> +      }
如果交易失敗，我們還需要發 `fetchSubscriprionByOrderNumber` request 嗎？
這邊的順序是否和發送 `fetchSubscriprionByOrderNumber` request 的順序交換？

2022-04-12 04:25 UTC, nickhsine commented on pages/subscribe/info.vue
>          )
想請問，這邊為何要打 api 去 encrypt tradeInfo ？

2022-04-12 04:27 UTC, nickhsine commented on pages/subscribe/return.vue
> +    if (req.method !== 'POST') redirect('/subscribe')
`return redirect('/subscribe')` 
請加上 `return` 確保後續程式碼不會被執行。

2022-04-12 06:46 UTC, v61265 commented on pages/subscribe/return.vue
> +      if (result.errors) throw new Error(result.errors[0].message)
這邊會特別處理是因為 `/api/graphql` 有可能把錯誤訊息包在回傳資料中，所以才抓出來傳給 `catch` 的部分。其他錯誤沒有這個問題，會直接進入 `catch` 之中。

2022-04-12 06:46 UTC, v61265 commented on pages/subscribe/return.vue
> +      }
因為紙本雜誌和這頁本來的設計稿上都需要交易 ID（也就是此處回傳的 `errorData.orderId`），這部分會存在 israfel 裡面，因此還是需要打 `fetchSubscriprionByOrderNumber` 拿到。雖然會員訂閱現在沒有，但以防哪天需求更改就只要改 UI 即可。

2022-04-12 06:46 UTC, v61265 commented on pages/subscribe/info.vue
>          )
這裡是禮義本來的寫法，當初應該就是要把 key 和 iv 藏起來，是否有需要一起在該 PR 中更改呢？

2022-04-12 06:46 UTC, v61265 commented on apollo/queries/memberSubscriptionQuery.gql
> +}
當初這樣寫是因為用 apollo 包好的方式打 gql 最方便，不過老實說也不太清楚選用 apollo 的時機

2022-04-12 06:55 UTC, nickhsine commented on pages/subscribe/return.vue
> +      if (result.errors) throw new Error(result.errors[0].message)
> 這邊會特別處理是因為 /api/graphql 有可能把錯誤訊息包在回傳資料中，所以才抓出來傳給 catch 的部分

2022-04-12 06:58 UTC, nickhsine commented on apollo/queries/memberSubscriptionQuery.gql
> +}
@kjwen310 
可以請教一下，使用 apollo 的時機嗎？

我會提出此疑慮的原因是，我記得凱傑說過 apollo 會有一層 cache。
但因為和 subscription query 有關的資訊不應該被 cache，
所以不曉得這邊使用 apollo 會不會有什麼副作用？

2022-04-12 07:00 UTC, nickhsine commented on pages/subscribe/info.vue
>          )
感覺改動幅度會頗大，先不要在這個 PR 修正好了。
感謝回覆

2022-04-12 07:03 UTC, nickhsine commented on pages/subscribe/return.vue
> +      }
我的意思是
Ln.66 - Ln.74 可否移到 Ln.35 ？

2022-04-12 07:11 UTC, v61265 commented on pages/subscribe/return.vue
> +      }
因為 `decryptInfoData` 在 L.n. 56 ，所以沒辦法。

2022-04-12 07:11 UTC, v61265 commented on pages/subscribe/return.vue
> +      if (result.errors) throw new Error(result.errors[0].message)
原來如此，確實沒想道有複數 error 的問題，那我改一下

2022-04-12 07:11 UTC, nickhsine commented on apollo/queries/memberSubscriptionQuery.gql
> +}
> 當初這樣寫是因為用 apollo 包好的方式打 gql 最方便

另外，也想問，此 PR 的 query 寫法，有用到 apollo 嗎？
現在的寫法是：
```
      const { data: result } = await axios({
        url: `${ISRAFEL_ORIGIN}/api/graphql`,
        method: 'post',
        data: {
          query: print(fetchSubscriprionByOrderNumber),
          variables: { orderNumber: MerchantOrderNo },
        },
        headers: {
          'content-type': 'application/json',
          'Cache-Control': 'no-cache',
        },
      })
```

和我不用 apollo 有什麼差別嗎？
不用 apollo 的寫法
```
      const query = `
query fetchSubscriprionByOrderNumber($orderNumber: String) {
  allSubscriptions(
    where: {
    orderNumber: $orderNumber
  }
  ) {
    id
    orderNumber
    frequency
    periodCreateDatetime
    periodFirstDatetime
    periodEndDatetime
    promoteId
  }
}
`
      const { data: result } = await axios({
        url: `${ISRAFEL_ORIGIN}/api/graphql`,
        method: 'post',
        data: {
          query,
          variables: { orderNumber: MerchantOrderNo },
        },
        headers: {
          'content-type': 'application/json',
          'Cache-Control': 'no-cache',
        },
      })
```

2022-04-12 07:15 UTC, nickhsine commented on pages/subscribe/return.vue
> +      }
可以改成：
```
      const infoData = req.body
      const newebpay = new NewebPay(NEWEBPAY_KEY, NEWEBPAY_IV)
      const decryptedTradeInfo = await newebpay.getDecryptedTradeInfo(
        infoData.TradeInfo
      )
      const MerchantOrderNo = JSON.parse(Object.keys(decryptedTradeInfo)[0])
        .Result.MerchantOrderNo

      if (infoData.Status !== 'SUCCESS') {
        return {
          status: infoData.Status,
          errorData: {
            orderId: decryptInfoData.orderNumber,
            message: infoData.Status,
          },
        }
      }
```
嗎？

2022-04-12 07:24 UTC, kjwen310 commented on apollo/queries/memberSubscriptionQuery.gql
> +}
是的，`apollo` 本身會有 cache，但這個 cache 可以被取消，以 `memberSubscription.gql` 內的 `fetchMemberBasicInfo` 這支 query 為例：

1. 在 `store/membership-subscribe.js` 使用時，是用 apollo 打資料，因此帶上 no-cache。([連結](https://github.com/mirror-media/mirror-media-nuxt/blob/dev/store/membership-subscribe.js#L22))
2. 在 `utils/memberSubscription.js` 使用時，是用 axios 打資料，沒有透過 apollo。([連結](https://github.com/mirror-media/mirror-media-nuxt/blob/dev/utils/memberSubscription.js#L144))

因此不透過 apollo 也是沒有問題的，應該只是習慣的寫法差異，apollo 有提供了既定的打 query 格式，但我們也可以自己撰寫通用的像 `fireGqlRequest` 使用。

另外如果不能被 cache 的 query，使用 `apollo` 時就必須帶上 `no-cache`，並且這部分比較適合不需要搭配 `fetchmore` 或 `smart query` 等情境 ( 因為載入更多時會需要` apollo` 的 cache )。

抱歉對週刊的流程沒有到很熟悉，這是目前看到的用法和一些覺得會影響的地方

2022-04-12 07:31 UTC, nickhsine commented on apollo/queries/memberSubscriptionQuery.gql
> +}
感謝 @kjwen310 回覆。
我想此 PR 並沒有用 apollo 去打資料。
因此，我覺得 GraphQL query 可以不用寫在 apollo 的檔案裡面（實際上的程式碼也是直接用 axios 去打的）。

所以，可以參考留言的改法修改：
```
      const query = `
query fetchSubscriprionByOrderNumber($orderNumber: String) {
  allSubscriptions(
    where: {
    orderNumber: $orderNumber
  }
  ) {
    id
    orderNumber
    frequency
    periodCreateDatetime
    periodFirstDatetime
    periodEndDatetime
    promoteId
  }
}
`
      const { data: result } = await axios({
        url: `${ISRAFEL_ORIGIN}/api/graphql`,
        method: 'post',
        data: {
          query,
          variables: { orderNumber: MerchantOrderNo },
        },
        headers: {
          'content-type': 'application/json',
          'Cache-Control': 'no-cache',
        },
      })
```

修改如下：
1. 不把 query 寫到 apollo 的檔案中
2. 不要 `import { fetchSubscriprionByOrderNumber } from '~/apollo/queries/memberSubscriptionQuery.gql'`（此動作會需要設定額外的 babel）
3. 不需要用到 `print` function 
4. 直接把 query 寫在 `pages/subscribe/return.vue` 中。

2022-04-12 07:36 UTC, v61265 commented on pages/subscribe/return.vue
> +      }
`MerchantOrderNo` 是對藍新那邊的代碼，和 israfel 紀錄的 `orderId` 不同，所以還是要經過 israfel 拿。

2022-04-12 07:50 UTC, nickhsine commented on pages/subscribe/return.vue
> +      }
兩個差別是什麼呢？

2022-04-12 17:05 UTC, v61265 commented on pages/subscribe/return.vue
> +      }
不好意思是我看錯，兩者沒有差別，目前已經照建議修改，感謝。

2022-04-13 06:14 UTC, nickhsine commented on pages/subscribe/return.vue
> +      }
這邊似乎沒有處理完？
應該要 throw error 吧？

2022-04-13 06:15 UTC, v61265 commented on pages/subscribe/return.vue
> +      }
對耶，感謝提醒！

2022-04-13 13:19 UTC, nickhsine commented on pages/subscribe/return.vue
> +        const data = await axios({
可以把這邊的 `data` rename 成 `axiosRes` 嗎？
這邊有好多的 `data`，很容易混肴。

2022-04-13 13:20 UTC, nickhsine commented
LGTM 💯 👍

2022-04-13 19:42 UTC, merged